# Generated by Django 4.1.1 on 2022-09-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('payment', '0001_initial'),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccomission',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.firm'),
        ),
        migrations.AddField(
            model_name='privatecomission',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.firm'),
        ),
        migrations.AddField(
            model_name='invoicefirm',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.viewer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.viewer'),
        ),
        migrations.AddField(
            model_name='comission',
            name='base_commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.publiccomission'),
        ),
    ]
