# Generated by Django 4.1.1 on 2022-09-16 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vebinar', '0002_rename_data_scheduler_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comission',
            new_name='Commission',
        ),
        migrations.RenameModel(
            old_name='PrivateComission',
            new_name='PrivateCommission',
        ),
        migrations.RenameModel(
            old_name='PublicComission',
            new_name='PublicCommission',
        ),
        migrations.RenameField(
            model_name='invoicefirm',
            old_name='is_paid',
            new_name='is_payment_transfered',
        ),
        migrations.RenameField(
            model_name='invoicefirm',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='viewer',
        ),
        migrations.RemoveField(
            model_name='invoicefirm',
            name='viewer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicefirm',
            name='date_of_payment_ITF_recieved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicefirm',
            name='date_of_payment_orginazer_recieved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicefirm',
            name='firm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.firm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicefirm',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicefirm',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='vebinar.subscription'),
        ),
        migrations.AddField(
            model_name='invoicefirm',
            name='vebinar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vebinar.vebinar'),
            preserve_default=False,
        ),
    ]
