# Generated by Django 4.1.1 on 2022-09-16 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vebinar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduler',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='price',
            new_name='amount_organizer_recieves',
        ),
        migrations.RemoveField(
            model_name='vebinar',
            name='firm',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='is_organized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='commission_ITF_receives',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='fee',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vebinar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vebinar',
            name='orginazer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vebinar',
            name='status',
            field=models.CharField(choices=[('appear', 'appear'), ('cancel', 'cancel'), ('delete', 'delete')], default='appear', max_length=20),
        ),
    ]
